### ISSUE TITLE
Add commands when players leave the server.

### ISSUE THREAD

**Issue by TWME-TW** [SirBlobman/JoinCommands#2]
Maybe plugin **Join Commands** can also add `leave commands`
🙂

**Comment by SirBlobman** [comment]
@TWME-TW Thank you for the request and sorry for the late reply. 

Unfortunately, leave commands would only be executable in the server console. Once the player has left the server, we can't really force them to run a command without causing issues. Also the plugin would need to be renamed and I can't think of a name at this time. 

I'll leave this open for now though.

**Comment by RedstoneFuture** [comment]
I also think that this does not meet the actual purpose of this dedicated plugin.
